name: deployReact
 
'on': 
  workflow_call: null 
  workflow_dispatch: null 
  push: 
    branches: 
      - master 
jobs: 
  DeployReact:  
    name: Deploying React 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: ReactDeploy 
        env: 
          SSH_KEY: ${{secrets.SSH_EC2}} 
          REACT_HOST: ${{ secrets.REACT_HOST }}
        run: | 
          echo $SSH_KEY | tr ' ' '\n' | base64 --decode > key1.pem 
          chmod 400 key1.pem 
          ssh -o StrictHostKeyChecking=no -i "key1.pem" ubuntu@$REACT_HOST './deploy.sh'